{{- $pdb := index .Values.podDisruptionBudgetOverrides (include "petclinic-service.name" .) }}
{{- if $pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "petclinic-service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ $pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "petclinic-service.selectorLabels" . | nindent 6 }}
{{- end }}
